# Pull the Node image from Docker Hub
FROM node:14-slim as build-stage

# Setting Working Directory
WORKDIR /usr/src/app

COPY package*.json ./
COPY ./yarn.lock ./

# Install Dependencies
RUN yarn
RUN yarn build

# Copy rest of the code to container
COPY . .

FROM nginx:1.17.0-alpine
COPY --from=build-stage /client/build /usr/share/nginx/html
EXPOSE 3000
CMD nginx -g 'daemon off;'