# Pull the Node image from Docker Hub
FROM --platform=linux/amd64 node:14.17.0-alpine

# Setting Working Directory
WORKDIR /usr/src/app

COPY package*.json ./
COPY ./yarn.lock ./

# Install Dependencies
RUN npm install
# Copy rest of the code to container
COPY . .

EXPOSE 3000

CMD ["npm","run","build"]