# Pull the Node image from Docker Hub
FROM node:14-slim as build-stage

# Setting Working Directory
WORKDIR /usr/src/app

COPY package*.json ./
COPY ./yarn.lock ./

# Install Dependencies
RUN yarn

# Copy rest of the code to container
COPY . .
RUN yarn build



### Second Stage ###
FROM caddy:2.1.1

ARG CADDYFILE
COPY ${CADDYFILE} /etc/caddy/Caddyfile

COPY --from=build-stage /usr/src/app/build/ /srv

EXPOSE 80

EXPOSE 443

