version: "3"
services:
  client:
    image: client-prod:${ENV}
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy-data:/data
      - caddy-config:/config
    networks:
      - mern-stack-net
  server:
    image: server
    restart: unless-stopped
    env_file: ./server/config.env
    ports:
      - "4000:4000"
    networks:
      - mern-stack-net
networks:
  mern-stack-net:
    driver: bridge
volumes:
  mongo-data:
    driver: local
  caddy-data:
    driver: local
  caddy-config:
    driver: local