version: "3"
services:
  client:
    image: client-dev
    ports:
      - "3000:3000"
    networks:
      -  mern-stack-net
    volumes:
      -  ./client/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server
    stdin_open: true
    tty: true

  server:
    image: server
    ports:
      - "4000:4000"
    env_file: ./server/config.env
    networks:
      - mern-stack-net
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mern-stack-net
    volumes:
      - mongo-data:/data/db

networks:
  mern-stack-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local